### ISSUE TITLE
FR: improve mutli-mon support

### ISSUE THREAD

**Issue by laur89** [DMBuce/i3b#1]
Currently multi-mon support is minimal; configuration centers specific screen only.

**Comment by DMBuce** [comment]
I just pushed commit 73e90512, which adds basic multi monitor support. It treats multiple monitors as one big display.

If you previously configured i3move with `i3move --gen > ~/.config/i3move`, your config will have an incorrect `--margins` setting and you will need to run that command again.

Sometime in the future I'm hoping to improve the behavior so that windows will snap to the edges when transitioning between monitors. Probably with a new option to switch the snapping behavior off.

**Comment by DMBuce** [comment]
I made some changes today that added proper multi-monitor support, with new options to control its behavior:

```
       -M, --compound-display

           Treat each monitor separately.  Compute distances and positions with
           respect to the monitor that contains the active window.  With --snap
           enabled, when a window that is snapped to a margin is moved towards an
           adjacent monitor, it will snap to that monitor's nearest margin.

           This is the default behavior.

       --no-compound-display

           Disable --compound-display and treat multiple monitors as one big
           monitor.
```

**Comment by DMBuce** [comment]
Also, I did not test a setup with multiple graphics cards. No idea how i3move will behave in such a situation. Feel free to open a new feature request if support for multiple graphics cards is desired.
